# Generated by Django 3.2.10 on 2024-04-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
