# Generated by Django 3.2.10 on 2024-03-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=models.ImageField(blank=True, default='gator-mascot-head-vector.png', null=True, upload_to=''),
        ),
    ]
