# Generated by Django 3.2.10 on 2024-03-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_author_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='gator_points',
            field=models.IntegerField(default=0),
        ),
    ]
