# Generated by Django 3.2.10 on 2024-04-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20240420_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
