# Generated by Django 3.2.10 on 2024-04-24 01:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0004_userpost_is_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='gatorpnts',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_names', models.CharField(max_length=100)),
                ('tot_gatorpnts', models.IntegerField(default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
