# Generated by Django 3.2.10 on 2024-04-06 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_author_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
